version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  geoserver:
    image: kartoza/geoserver:2.27.0
    container_name: gis-geoserver
    restart: always
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER:-admin}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD:-geoserver}
      - INITIAL_MEMORY=${INITIAL_MEMORY:-2G}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY:-4G}
    ports:
      - "8085:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      target: development # Especifica o estágio de desenvolvimento
    container_name: gis-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - geoserver
    environment:
      - VITE_GEOSERVER_URL=http://localhost:8085/geoserver/mato_grosso/wms

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  geoserver_data:
    driver: local
